# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('representatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Introduced'), (2, 'Reported'), (3, 'Passed House'), (4, 'Failed House'), (5, 'Passed Senate'), (6, 'Failed Senate')], default=0)),
                ('bill_type', models.CharField(max_length=100)),
                ('introduced_date', models.DateTimeField()),
                ('current_status_date', models.DateTimeField()),
                ('govtrack_id', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(0, 'Not Voting'), (1, 'Present'), (2, 'Aye'), (3, 'No')], default=0)),
                ('date_created', models.DateTimeField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Bill')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representatives.Representative')),
            ],
        ),
    ]
