# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 23:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 15, 23, 33, 32, 8431, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
