# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 23:29
from __future__ import unicode_literals

from django.db import migrations
import slothauth.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='one_time_authentication_key',
            field=slothauth.utils.RandomField(default='asdfasdfkljhasdf', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='password_reset_key',
            field=slothauth.utils.RandomField(default='123423423sdafsdfasd', max_length=32),
            preserve_default=False,
        ),
    ]
