# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 01:18
from __future__ import unicode_literals

from django.db import migrations
import slothauth.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160515_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=slothauth.utils.CiEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
